name: Home Maintenance

on:
  push:
    branches: [main]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    name: create maintenance issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: home_maintenance_action
        uses: maxbeizer/home_maintenance@1e4b72c34931b175e7b26522a4332a2916070461
        with:
          repo-nwo: 'maxbeizer/home_maintenance_test'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          time-frame: 'all'
          path-to-data: 'tasks.csv'
