name: Home Maintenance

on:
  push:
    branches: [main]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    name: create maintenance issues
    steps:
      - name: home_maintenance_action
        uses: maxbeizer/home_maintenance@C2d13daa6bfe39e21871ea09591d482fb214da697
        with:
          repo-nwo: 'maxbeizer/home_maintenance_test'
          github-token: ${{ secrets.GITHUB_TOKEN }}
