name: Home Maintenance

on:
  push:
    branches: [main]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    name: create maintenance issues
    steps:
      - name: home_maintenance_action
        uses: maxbeizer/home_maintenance@e3d5a413aac195bb8f742b1b236f93ef2ddcca3a
        with:
          repo-nwo: 'maxbeizer/home_maintenance_test'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          time-frame: 'all'
          path-to-data: './tasks.csv'
